# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mail.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import smtplib
from email.message import EmailMessage
from pathlib import Path
from string import Template


# gui created using qt 5 
while(1):
    class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
            MainWindow.setObjectName("MainWindow")
            MainWindow.resize(1153, 803)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
            MainWindow.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            font.setItalic(False)
            font.setStrikeOut(False)
            MainWindow.setFont(font)
            self.centralwidget = QtWidgets.QWidget(MainWindow)
            self.centralwidget.setObjectName("centralwidget")
            self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.plainTextEdit.setGeometry(QtCore.QRect(150, 430, 981, 241))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
            self.plainTextEdit.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            font.setItalic(False)
            font.setStrikeOut(False)
            self.plainTextEdit.setFont(font)
            self.plainTextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
            self.plainTextEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
            self.plainTextEdit.setPlainText("")
            self.plainTextEdit.setObjectName("plainTextEdit")
            self.label = QtWidgets.QLabel(self.centralwidget)
            self.label.setGeometry(QtCore.QRect(10, 100, 111, 51))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
            self.label.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            font.setBold(True)
            font.setItalic(False)
            font.setWeight(75)
            font.setStrikeOut(False)
            self.label.setFont(font)
            self.label.setObjectName("label")
            self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
            self.lineEdit.setGeometry(QtCore.QRect(150, 100, 431, 51))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
            self.lineEdit.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            font.setItalic(False)
            font.setStrikeOut(False)
            self.lineEdit.setFont(font)
            self.lineEdit.setText("")
            self.lineEdit.setObjectName("lineEdit")
            ###################################self.lineEdit.setEchoMode(QLineEdit.Password)
            self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
            self.label_2 = QtWidgets.QLabel(self.centralwidget)
            self.label_2.setGeometry(QtCore.QRect(10, 20, 71, 51))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
            self.label_2.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            font.setBold(True)
            font.setItalic(False)
            font.setWeight(75)
            font.setStrikeOut(False)
            self.label_2.setFont(font)
            self.label_2.setObjectName("label_2")
            self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
            self.lineEdit_2.setGeometry(QtCore.QRect(150, 20, 431, 51))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
            self.lineEdit_2.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            font.setItalic(False)
            font.setStrikeOut(False)
            self.lineEdit_2.setFont(font)
            self.lineEdit_2.setText("")
            self.lineEdit_2.setObjectName("lineEdit_2")
            self.label_3 = QtWidgets.QLabel(self.centralwidget)
            self.label_3.setGeometry(QtCore.QRect(10, 180, 91, 51))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
            self.label_3.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            font.setBold(True)
            font.setItalic(False)
            font.setWeight(75)
            font.setStrikeOut(False)
            self.label_3.setFont(font)
            self.label_3.setObjectName("label_3")
            self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
            self.lineEdit_3.setGeometry(QtCore.QRect(150, 180, 431, 51))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
            self.lineEdit_3.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            font.setItalic(False)
            font.setStrikeOut(False)
            self.lineEdit_3.setFont(font)
            self.lineEdit_3.setText("")
            self.lineEdit_3.setObjectName("lineEdit_3")
            self.label_4 = QtWidgets.QLabel(self.centralwidget)
            self.label_4.setGeometry(QtCore.QRect(10, 430, 91, 51))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
            self.label_4.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            font.setBold(True)
            font.setItalic(False)
            font.setWeight(75)
            font.setStrikeOut(False)
            self.label_4.setFont(font)
            self.label_4.setObjectName("label_4")
            self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
            self.calendarWidget.setGeometry(QtCore.QRect(640, 20, 491, 321))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
            self.calendarWidget.setSizePolicy(sizePolicy)
            self.calendarWidget.setObjectName("calendarWidget")
            self.pushButton = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton.setGeometry(QtCore.QRect(530, 680, 221, 51))
            font = QtGui.QFont()
            font.setPointSize(14)
            font.setBold(True)
            font.setItalic(False)
            font.setWeight(75)
            font.setStrikeOut(False)
            self.pushButton.setFont(font)
            self.pushButton.setObjectName("pushButton")
            self.widget = QtWidgets.QWidget(self.centralwidget)
            self.widget.setGeometry(QtCore.QRect(130, 510, 120, 80))
            self.widget.setObjectName("widget")
            self.label_5 = QtWidgets.QLabel(self.centralwidget)
            self.label_5.setGeometry(QtCore.QRect(10, 260, 91, 51))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
            self.label_5.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            font.setBold(True)
            font.setItalic(False)
            font.setWeight(75)
            font.setStrikeOut(False)
            self.label_5.setFont(font)
            self.label_5.setObjectName("label_5")
            self.label_6 = QtWidgets.QLabel(self.centralwidget)
            self.label_6.setGeometry(QtCore.QRect(10, 330, 91, 51))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
            self.label_6.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            font.setBold(True)
            font.setItalic(False)
            font.setWeight(75)
            font.setStrikeOut(False)
            self.label_6.setFont(font)
            self.label_6.setObjectName("label_6")
            self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
            self.lineEdit_4.setGeometry(QtCore.QRect(150, 260, 431, 51))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
            self.lineEdit_4.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            font.setItalic(False)
            font.setStrikeOut(False)
            self.lineEdit_4.setFont(font)
            self.lineEdit_4.setText("")
            self.lineEdit_4.setObjectName("lineEdit_4")
            self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
            self.lineEdit_5.setGeometry(QtCore.QRect(150, 340, 431, 51))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
            self.lineEdit_5.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            font.setItalic(False)
            font.setStrikeOut(False)
            self.lineEdit_5.setFont(font)
            self.lineEdit_5.setText("")
            self.lineEdit_5.setObjectName("lineEdit_5")
            MainWindow.setCentralWidget(self.centralwidget)
            self.menubar = QtWidgets.QMenuBar(MainWindow)
            self.menubar.setGeometry(QtCore.QRect(0, 0, 1153, 34))
            self.menubar.setObjectName("menubar")
            MainWindow.setMenuBar(self.menubar)
            self.statusbar = QtWidgets.QStatusBar(MainWindow)
            self.statusbar.setObjectName("statusbar")
            MainWindow.setStatusBar(self.statusbar)

            self.retranslateUi(MainWindow)
            QtCore.QMetaObject.connectSlotsByName(MainWindow)

        


            self.pushButton.clicked.connect(self.sendmail)   # acton listner for the send button. send th email when button is click

        def retranslateUi(self, MainWindow):
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
            self.label.setText(_translate("MainWindow", "Password:"))
            self.label_2.setText(_translate("MainWindow", "Email:"))
            self.label_3.setText(_translate("MainWindow", "From:"))
            self.label_4.setText(_translate("MainWindow", "Message:"))
            self.pushButton.setText(_translate("MainWindow", "Send"))
            self.label_5.setText(_translate("MainWindow", "To:"))
            self.label_6.setText(_translate("MainWindow", "Subject:"))
            #password=self.lineEdit.text()
            #emailaddr=self.lineEdit_2.text()
            #_from=self.lineEdit_3.text()
            #to=self.lineEdit_4.text()
            #Subject=self.lineEdit_5.text()

        def sendmail(self):   #send email using python smtp library 
            password=self.lineEdit.text()   # get password from that particular field 
            emailaddr=self.lineEdit_2.text()  # get email address from text field 
            _from=self.lineEdit_3.text()   # get sender name 
            to=self.lineEdit_4.text()   # get receiver address
            subject=self.lineEdit_5.text()  # get subject of the email
            message= self.plainTextEdit.toPlainText()   # get the message from the text region 
            html= Template(Path('index.html').read_text())
            email= EmailMessage()
            email['from']= _from
            email['to']= to
            email['subject']= subject

            email.set_content(html.substitute({'name': message}), 'html')   # replace the name variable in the html file with the message 

            with smtplib.SMTP(host='smtp.gmail.com', port=587) as smtp:   # uses google server and port 587
                smtp.ehlo()
                smtp.starttls()   # ensure secure connection 
                smtp.login(emailaddr,password) # logins into gmail 
                smtp.send_message(email)
                print("Email successfully sent")  # notify user 


    if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
